dist: trusty
sudo: required

language: c

addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - autoconf
    - unzip
    - wget
    - git

cache:
  apt: true
  directories:
  - $HOME/.opam
  - coq
  - HoTT

before_cache:
  - rm -rf $HOME/.opam/log/

env:
  global:
  - NJOBS=2
  # system is == 4.02.3
  - COMPILER="system"
  - CAMLP5_VER="6.14"
  matrix:
    - TARGET="IR"
    - TARGET="trunk"
    - TARGET="8.6"

install:
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- eval $(opam config env)
- opam config list
- opam install -j ${NJOBS} -y camlp5.${CAMLP5_VER} ocamlfind ${EXTRA_OPAM}
- opam list

- ./build-dependencies.sh

script:
- export PATH="$(pwd)/coq/bin/:$(pwd)/HoTT/:$PATH"
- ./build-HoTTClasses.sh
