name: 'Workspace Artifact'
description: 'Upload or download workspace artifacts'
inputs:
  action:
    description: 'Action to perform: upload or download'
    required: true
  coq_version:
    description: 'Coq version for artifact naming'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Tar workspace files
      if: inputs.action == 'upload'
      shell: bash
      run: tar -cf workspace.tar .
    - name: Upload workspace artifact
      if: inputs.action == 'upload'
      uses: actions/upload-artifact@v4
      with:
        name: workspace-${{ inputs.coq_version }}
        path: workspace.tar
    - name: Download workspace artifact
      if: inputs.action == 'download'
      uses: actions/download-artifact@v4
      with:
        name: workspace-${{ inputs.coq_version }}
    - name: Unpack workspace files
      if: inputs.action == 'download'
      shell: bash
      run: tar -xf workspace.tar