name: 'Set Coq Version'
description: 'Set the COQ_VERSION environment variable from JSON configuration'
inputs:
  coq-version-dummy:
    description: 'The coq version identifier (e.g., 8.20, 9.0, 9.1, dev)'
    required: true
  coq-versions-json:
    description: 'JSON object containing coq version configuration with test/build-with-workspace/docs categories'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Parse Coq version from JSON
      shell: bash
      run: |
        # The dummy is now the actual version, just validate it exists in our config
        version="${{ inputs.coq-version-dummy }}"
        
        # Validate the version exists in our configuration
        found=$(echo '${{ inputs.coq-versions-json }}' | jq -r --arg v "$version" '
          [.test[], .["build-with-workspace"][], .docs[]] | 
          if any(. == $v) then "true" else "false" end
        ')
        
        if [ "$found" != "true" ]; then
          echo "ERROR: Version $version not found in configuration"
          echo "Available versions: $(echo '${{ inputs.coq-versions-json }}' | jq -r '[.test[], .["build-with-workspace"][], .docs[]] | join(", ")')"
          exit 1
        fi
        
        echo "COQ_VERSION=$version" >> $GITHUB_ENV
        echo "Set COQ_VERSION to: $version"